/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...path]': RouteRecordInfo<'/[...path]', '/:path(.*)', { path: ParamValue<true> }, { path: ParamValue<false> }>,
    '/about/': RouteRecordInfo<'/about/', '/about', Record<never, never>, Record<never, never>>,
    '/about/site': RouteRecordInfo<'/about/site', '/about/site', Record<never, never>, Record<never, never>>,
    '/archives/': RouteRecordInfo<'/archives/', '/archives', Record<never, never>, Record<never, never>>,
    '/bill/': RouteRecordInfo<'/bill/', '/bill', Record<never, never>, Record<never, never>>,
    '/categories/': RouteRecordInfo<'/categories/', '/categories', Record<never, never>, Record<never, never>>,
    '/links/': RouteRecordInfo<'/links/', '/links', Record<never, never>, Record<never, never>>,
    '/page/[page]': RouteRecordInfo<'/page/[page]', '/page/:page', { page: ParamValue<true> }, { page: ParamValue<false> }>,
    '/posts/getting-started-of-vercel-serverless-function': RouteRecordInfo<'/posts/getting-started-of-vercel-serverless-function', '/posts/getting-started-of-vercel-serverless-function', Record<never, never>, Record<never, never>>,
    '/posts/graduate-one': RouteRecordInfo<'/posts/graduate-one', '/posts/graduate-one', Record<never, never>, Record<never, never>>,
    '/posts/idris2-getting-started': RouteRecordInfo<'/posts/idris2-getting-started', '/posts/idris2-getting-started', Record<never, never>, Record<never, never>>,
    '/posts/koi-love': RouteRecordInfo<'/posts/koi-love', '/posts/koi-love', Record<never, never>, Record<never, never>>,
    '/posts/latex-guide': RouteRecordInfo<'/posts/latex-guide', '/posts/latex-guide', Record<never, never>, Record<never, never>>,
    '/posts/video-server-exp': RouteRecordInfo<'/posts/video-server-exp', '/posts/video-server-exp', Record<never, never>, Record<never, never>>,
    '/projects/': RouteRecordInfo<'/projects/', '/projects', Record<never, never>, Record<never, never>>,
    '/tags/': RouteRecordInfo<'/tags/', '/tags', Record<never, never>, Record<never, never>>,
  }
}
