name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: 🍳 Build on node ${{ matrix.node_version }} and ${{ matrix.os }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest]
        node_version: [16.x]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          registry-url: https://registry.npmjs.org/

      - name: 📦 Install Dependencies
        run: npm i

      - name: Fix Bugs
        run: cp -rf valaxy_dist/* node_modules/valaxy/dist/

      - name: 🌌 Build Valaxy Blog
        run: npm run build
      
      - name: GA
        run: node ./ga.js

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.ftp_server }}
          username: ${{ secrets.ftp_username }}
          password: ${{ secrets.ftp_password }}
          local-dir: ./dist/
          server-dir: /wwwroot/rotcool/blog/